spring:
  application:
    name: OrderService

#Database Configurations
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#######################

server:
  port: 8086